version: "3.5"

services:
  php:
    image: mctekk/phalconphp:latest
    volumes:
      - .:/app
    tty: true
    ports:
      - "9000:9000"
    networks:
      - local-network

  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    links:
        - php
    volumes:
        - .:/app
        - ./storage/ci/apicms.blinked.gg.conf:/etc/nginx/conf.d/default.conf
    networks:
      - local-network
      - public-network

networks:
  local-network:
  public-network: